copy /y frontend_5.0.mo ..\..\centos_7_zabbix_5.0.x_mysql\patch
copy /y frontend_6.0.mo ..\..\rocky_8_zabbix_6.0.x_mysql\patch
copy /y frontend_6.0.mo ..\..\rocky_8_zabbix_6.0.x_pgsql\patch
copy /y frontend_6.0.mo ..\..\zabbix_6.0.x_docker\patch
copy /y frontend_6.0.mo ..\..\zabbix_6.0.x_dockerfile\zbx\patch
copy /y docker-compose-linux-x86_64* ..\..\zabbix_6.0.x_docker\patch
copy /y docker-compose-linux-x86_64* ..\..\zabbix_6.0.x_dockerfile\zbx\patch
copy /y create_server_6.0-latest_mysql.sql.gz ..\..\rocky_8_zabbix_6.0.x_mysql\mysql
copy /y create_server_6.0-latest_mysql.sql.gz ..\..\zabbix_6.0.x_dockerfile\zbx\trans
copy /y create_server_6.0-latest_pgsql.sql.gz ..\..\rocky_8_zabbix_6.0.x_pgsql\pgsql
copy /y create_server_6.0-latest_pgsql.sql.gz ..\..\zabbix_6.0.x_dockerfile\zbx\trans
copy /y frontend_7.0.mo ..\..\rocky_8_zabbix_7.0.x_mysql\patch
copy /y frontend_7.0.mo ..\..\rocky_8_zabbix_7.0.x_pgsql\patch
copy /y frontend_7.0.mo ..\..\centos_7_zabbix_7.0.x_mysql\patch
copy /y frontend_7.0.mo ..\..\centos_7_zabbix_7.0.x_pgsql\patch
copy /y frontend_7.0.mo ..\..\zabbix_7.0.x_docker\patch
copy /y frontend_7.0.mo ..\..\zabbix_7.0.x_dockerfile\zbx\patch
copy /y frontend_7.0.mo ..\..\zabbix_7.0.x_build\pgsql\patch
copy /y frontend_7.0.mo ..\..\zabbix_7.0.x_build\mariadb\patch
copy /y docker-compose-linux-x86_64* ..\..\zabbix_7.0.x_docker\patch
copy /y docker-compose-linux-x86_64* ..\..\zabbix_7.0.x_dockerfile\zbx\patch
copy /y create_server_7.0-latest_mysql.sql.gz ..\..\rocky_8_zabbix_7.0.x_mysql\mysql
copy /y create_server_7.0-latest_mysql.sql.gz ..\..\centos_7_zabbix_7.0.x_mysql\mysql
copy /y create_server_7.0-latest_mysql.sql.gz ..\..\zabbix_7.0.x_dockerfile\zbx\trans
copy /y create_server_7.0-latest_mysql.sql.gz ..\..\zabbix_7.0.x_build\mariadb\mysql
copy /y create_server_7.0-latest_pgsql.sql.gz ..\..\rocky_8_zabbix_7.0.x_pgsql\pgsql
copy /y create_server_7.0-latest_pgsql.sql.gz ..\..\centos_7_zabbix_7.0.x_pgsql\pgsql
copy /y create_server_7.0-latest_pgsql.sql.gz ..\..\zabbix_7.0.x_dockerfile\zbx\trans
copy /y create_server_7.0-latest_pgsql.sql.gz ..\..\zabbix_7.0.x_build\pgsql\pgsql
copy /y .env_shell ..\..\rocky_8_zabbix_7.0.x_mysql\patch
copy /y .env_shell ..\..\rocky_8_zabbix_7.0.x_pgsql\patch
copy /y .env_shell ..\..\centos_7_zabbix_7.0.x_mysql\patch
copy /y .env_shell ..\..\centos_7_zabbix_7.0.x_pgsql\patch
copy /y .env_shell ..\..\zabbix_7.0.x_docker\patch
copy /y .env_shell ..\..\zabbix_7.0.x_dockerfile\zbx\patch
copy /y .env_shell ..\..\zabbix_7.0.x_build\pgsql\patch
copy /y .env_shell ..\..\zabbix_7.0.x_build\mariadb\patch

::copy /y snmptrapd.conf ..\..\centos_7_zabbix_5.0.x_mysql\snmptrap
::copy /y snmptrapd.conf ..\..\centos_7_zabbix_7.0.x_mysql\snmptrap
::copy /y snmptrapd.conf ..\..\centos_7_zabbix_7.0.x_pgsql\snmptrap
::copy /y snmptrapd.conf ..\..\kylin_v10_zabbix_7.0.x_mysql\snmptrap
::copy /y snmptrapd.conf ..\..\kylin_v10_zabbix_7.0.x_pgsql\snmptrap
::copy /y snmptrapd.conf ..\..\rocky_8_zabbix_6.0.x_mysql\snmptrap
::copy /y snmptrapd.conf ..\..\rocky_8_zabbix_6.0.x_pgsql\snmptrap
::copy /y snmptrapd.conf ..\..\rocky_8_zabbix_7.0.x_mysql\snmptrap
::copy /y snmptrapd.conf ..\..\rocky_8_zabbix_7.0.x_pgsql\snmptrap
::copy /y snmptrapd.conf ..\..\rocky_9_zabbix_7.0.x_pgsql\snmptrap

::copy /y zabbix_trap_receiver.pl ..\..\centos_7_zabbix_5.0.x_mysql\snmptrap
::copy /y zabbix_trap_receiver.pl ..\..\centos_7_zabbix_7.0.x_mysql\snmptrap
::copy /y zabbix_trap_receiver.pl ..\..\centos_7_zabbix_7.0.x_pgsql\snmptrap
::copy /y zabbix_trap_receiver.pl ..\..\kylin_v10_zabbix_7.0.x_mysql\snmptrap
::copy /y zabbix_trap_receiver.pl ..\..\kylin_v10_zabbix_7.0.x_pgsql\snmptrap
::copy /y zabbix_trap_receiver.pl ..\..\rocky_8_zabbix_6.0.x_mysql\snmptrap
::copy /y zabbix_trap_receiver.pl ..\..\rocky_8_zabbix_6.0.x_pgsql\snmptrap
::copy /y zabbix_trap_receiver.pl ..\..\rocky_8_zabbix_7.0.x_mysql\snmptrap
::copy /y zabbix_trap_receiver.pl ..\..\rocky_8_zabbix_7.0.x_pgsql\snmptrap
::copy /y zabbix_trap_receiver.pl ..\..\rocky_9_zabbix_7.0.x_pgsql\snmptrap