# Example configuration file for snmptrapd
#
# No traps are handled by default, you must edit this file!
#
# 启用调试信息（可选） 
# debugFlag=ALL 
# 创建一个 SNMPv3 用户
createUser -e 0x80001F88806452A1147174A46100000000 zabbix MD5 "Admin@zabbix" DES "Admin@zabbix"
# 指定如何处理来自特定用户的陷阱
authUser log,execute zabbix
authCommunity   log,execute,net public
# traphandle SNMPv2-MIB::coldStart    /usr/bin/bin/my_great_script cold
perl do "/usr/bin/zabbix_trap_receiver.pl"
# [root@localhost snmp]# snmptrap -v3 -e 0x80001F88806452A1147174A46100000000 -a MD5 -A Admin@zabbix -x DES -X Admin@zabbix -l authPriv -u zabbix 127.0.0.1 0 linkDown.0

