id              postgresql
major           16
data_default    /var/pgsql/data
package         postgresql-upgrade
engine          /usr/lib64/pgsql/postgresql-16/bin
description     "Upgrade data from system PostgreSQL version (PostgreSQL 16)"
redhat_sockets_hack no
